name: サーバーの初期化依頼
description: CoderDojo のサーバーを初期化（削除して作り直し）するための依頼フォームです
title: サーバーの初期化依頼
labels: ["サーバー初期化依頼"]
assignees: ["yasulab"]
body:
  - type: markdown
    attributes:
      value: |
        初期化すると、**サーバーの中のデータはすべて消えます**。必要なデータは、事前にバックアップをお取りください。

  - type: input
    id: dojo-name
    attributes:
      label: 道場名
      description: 先頭の CoderDojo は省いて、道場名だけをお書きください。
      placeholder: 那覇
    validations:
      required: true

  - type: input
    id: applicant-name
    attributes:
      label: 申請者名
      placeholder: 安川要平
    validations:
      required: true

  - type: input
    id: ip-address
    attributes:
      label: IPアドレス
      description: "[サーバーの一覧表](https://github.com/coderdojo-japan/dojopaas/blob/gh-pages/instances.csv)からご確認いただけます。"
      placeholder: 133.242.xxx.xxx
    validations:
      required: true

  - type: textarea
    id: comment
    attributes:
      label: コメント欄（任意）
      description: 困っていること・経緯など、何かあればご自由にお書きください。
    validations:
      required: false
